version: "3.9"
   
services:
  web:
    image: localhost:5000/docker_homework_web:0.1 
    ports:
      - "80:80"
    networks:
      - frontnet
  db:
    image: localhost:5000/postgres:12.10
    environment:
      - POSTGRES_NAME=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
    networks:
      - backnet
  back:
    image: localhost:5000/docker_homework_back:0.1 
    command: ["/bin/bash", "-c", "python manage.py migrate && exec python manage.py runserver 0.0.0.0:8000"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backnet
      - frontnet

networks:
    frontnet:
        driver: bridge
    backnet:
        driver: bridge
